spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gong-check;MODE=MYSQL;
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

server:
  port: 8080
