spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 60MB

file:
  upload-dir: /home/ubuntu/images/
  server-path: https://image.gongcheck.day/images/

server:
  port: 8080
