spring:
  sql:
    init:
      schema-locations: classpath:schema_local.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  output:
    ansi:
      enabled: always

security:
  jwt:
    token:
      secret-key: Z29uZy1jaGVjay1nb25nLWNoZWNrLWdvbmctY2hlY2stZ29uZy1jaGVjay1nb25nLWNoZWNrLWdvbmctY2hlY2stZ29uZy1jaGVjay1nb25nLWNoZWNrCg==
      expire-time: 3600000
  hash:
    secret-key: 12345678901234567890123456789012

github:
  client:
    id: client_id
    secret: client_secret
  url:
    token: https://github.com/login/oauth/access_token
    profile: https://api.github.com/user

file:
  upload-url: http://localhost:7070

server:
  port: 7070
